name: CI
on:
  workflow_dispatch:
    inputs:
      level:
        description: Logging Level
        required: true
        default: INFO
        type: choice
        options:
          - CRITICAL
          - FATAL
          - ERROR
          - WARNING
          - WARN
          - INFO
          - DEBUG
          - NOTSET
      pool:
        description: Number of threads
        required: true
        default: 8
      retry:
        description: Number of retries
        required: true
        default: 3
      time:
        description: Update wait time
        required: true
        default: 86400
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          choco install wget
          git fetch origin data && git worktree add -b data data origin/data
          cd data
          wget https://github.com/AGWA/git-crypt/releases/download/0.7.0/git-crypt-0.7.0-x86_64.exe -O git-crypt.exe
          python -c "open('KEY','wb').write(bytes.fromhex('${{ secrets.KEY }}'))"
          ./git-crypt unlock KEY
          cd ..
          python main.py -l ${{ github.event.inputs.level || 'INFO' }} -p ${{ github.event.inputs.pool || 8 }} -r ${{ github.event.inputs.retry || 3 }} -t ${{ github.event.inputs.time || 1 }}
          python push.py
          python push.py
          cd data
          git add appinfo.json userinfo.json
          git commit --no-verify -m "update"
          git push --force origin data